### ISSUE TITLE
Cannot generate Pull Requests from Bloom

### ISSUE THREAD

**Issue by thomas-moulard** [ros-infrastructure/bloom#256]
I enter my username, password and I get the following message:

```
Github username [moulard]: thomas-moulard
Github password (never stored): 
Failed to create a new oauth authorization: 401 Unauthorized
```

I strongly suspect this is due to the fact I use two-factor authentication on my account.

**Comment by jonbinney** [comment]
The new error message helps a lot, but I can't find the format for `~/.config/bloom` documented anywhere except in this issue. Are `github_user` and `oauth_token` the only two supported keys? Would there be any reason for `~/.config/bloom` to exist besides github tokens? (Once I understand this I'll try adding instructions on the ROS wiki for manually adding a github token to bloom, since I always forget how to do this.)

**Comment by wjwwood** [comment]
@jonbinney I do not believe the format for `~/.config/bloom` is documented. Currently nothing else can go in there other than the username and auth token, and the file type is JSON.

**Comment by jonbinney** [comment]
I created a (very short) tutorial here: http://wiki.ros.org/bloom/Tutorials/GithubManualAuthorization and added it to the list of bloom tutorials on the wiki.

**Comment by wjwwood** [comment]
Thanks @jonbinney, can this be closed?

**Comment by jonbinney** [comment]
Yeup

**Comment by DLu** [comment]
This might need to be revisited. I had two factor authentication turned on, and got this
```
==> git push --dry-run
Username for 'https://github.com': DLu
Password for 'https://DLu@github.com': 
remote: Invalid username or password.
fatal: Authentication failed for 'https://github.com/ros-gbp/urdf_tutorial-release.git/'
Cannot push to remote release repository.
```
I turned it off and it worked fine. 

```
! ~/ > bloom-release --version
0.5.21
! ~/ > more .config/bloom 
{"github_user": "DLu", "oauth_token": "1337hax0r"}

```

**Comment by jonbinney** [comment]
@dlu did you follow the tutorial for adding an authentication token for bloom?

**Comment by DLu** [comment]
I did awhile ago...my key is named bloom-0.5.11

**Comment by jonbinney** [comment]
That key is still in `~/.config/bloom` and authentication is still failing? :-(

**Comment by DLu** [comment]
Yes, and it says the key has been used recently/today. So its at least partially getting through, it seems.

**Comment by jonbinney** [comment]
I think that github may have changed the default permissions that authentication tokens get. Can you try creating a new key, making sure that the "repo" box is checked under the permissions for that key?

**Comment by DLu** [comment]
I though that might be it and turned on all permissions. 

I made a new key, and this time it didn't prompt me for a pass at all. 
```
==> git push --dry-run
remote: Invalid username or password.
fatal: Authentication failed for 'https://github.com/wu-robotics/navigation_layers_release.git/'
Cannot push to remote release repository.

```

**Comment by jonbinney** [comment]
Do you actually have push permissions to navigation_layers_release? :-P

**Comment by DLu** [comment]
I just released [an hour ago](https://github.com/wu-robotics/navigation_layers_release/commit/c9c865d21cd0738dab101fbf10824adab3756c9d) when I had 2 factor turned off.

**Comment by tfoote** [comment]
@DLu since i've turned on 2 fractor authentification I've always used the ssh urls for git access. The token works for the API to make the PRs.

**Comment by wjwwood** [comment]
@DLu which part of bloom is failing? Based on the `git push --dry-run` part, I don't believe that is using your bloom two factor stuff. I think it's more likely you have a `~/.netrc` file setup and when you enabled your two-factor it was no longer giving the correct password. It fails because it is trying to push the `https://` version of the url and then fails.

**Comment by wjwwood** [comment]
I think it's likely that if you clone that release repository and then try to do `git push --dry-run` in the directory, it might fail (of course only when you have two factor setup).

**Comment by DLu** [comment]
@tfoote I thought you weren't supposed to use ssh URLs for bloom. 

@wjwwood 
```
! ~/ > ls -al ~/.netrc
ls: cannot access /home/dlu/.netrc: No such file or directory

```

`git push --dry-run` works when in an ssh cloned repo, but not in a https cloned version. 

So should I be changing my release repository to ssh:... in bloom?

**Comment by wjwwood** [comment]
> but not in a https cloned version.

That's because of the two-factor. Does it ask you for your password before failing in bloom?

**Comment by wjwwood** [comment]
You can use the release push url setting to push with ssh even when using https (you should be using https in the release repository url).

**Comment by mikepurvis** [comment]
Despite that [the REP recommends a publicly readable (thus, HTTP URL)](http://www.ros.org/reps/rep-0137.html#release-file), it's perfectly possible to place SSH urls directly into your rosdistro— we've always done this for our private source, eg:

https://github.com/clearpathrobotics/public-rosdistro/blob/d135371ec71ce3a2112ca144f74567c2ed2b0083/indigo/distribution.yaml#L177

Bloom, the buildfarm, rosinstall_generator, etc all cope perfectly fine with this, as long as the appropriate users (eg, on the buildslaves) have SSH keys set up so that they can clone the repo.

**Comment by wjwwood** [comment]
You should not use non-https urls when submitting to our repository. But as @mikepurvis said it would work with the tools.

If you only want to authenticate with ssh then you should use the options provided in bloom to do so, i.e. the "Release Repository Push URL" setting that you're prompted for when setting or editing the track configurations (use `-e` when running bloom to change the settings before blooming) or by using the temporary `--override-release-repository-push-url`.

**Comment by jonbinney** [comment]
You can also force git to always use ssh even for https urls. I have this in my git config file:
```
# Always use ssh for github, even if the remote URL uses
# https or git
[url "git@github.com:"]
  insteadOf = git://github.com/
[url "git@github.com:"]
  insteadOf = https://github.com/
```

**Comment by wjwwood** [comment]
@jonbinney That's awesome, I didn't know about it. I'm gonna use that instead of a `~/.netrc` with an API key now 😄.

**Comment by davetcoleman** [comment]
fyi I added a very simple bash script to the [tutorial](http://wiki.ros.org/bloom/Tutorials/GithubManualAuthorization) just now for automatically setting up the required bloom config.
