### ISSUE TITLE
Patches not being applied in libg2o

### ISSUE THREAD

**Issue by mikepurvis** [ros-infrastructure/bloom#378]
I forked the `lib2o-release` repo so that I could add an additional patch to it, to disable building the apps and examples:

https://github.com/mikepurvis/libg2o-release/blob/patches/release/libg2o/0014-Disable-apps-examples.patch

I did this by following the usual third party release scheme of checking out the release branch, committing the change, and running `git-bloom-patch export`. However, successive releases from this repo don't seem to include the patch. You can see the change as commited by me in the `release/libg2o` branch:

https://github.com/mikepurvis/libg2o-release/blob/release/libg2o/CMakeLists.txt#L159

But in `release/indigo/libg2o`, the patch has not been applied:

https://github.com/mikepurvis/libg2o-release/blob/release/indigo/libg2o/CMakeLists.txt#L172

It's unclear to me if this is a bug or a mistake on my part.

**Comment by wjwwood** [comment]
Sorry it took so long to get back to you.

I think your issue is that the `release/package_name` branch is no longer used by bloom (it used to though). You'd need to update the `release/<rosdistro>/<package_name>` branch instead. The nominal process right now is `upstream` -> `release/<rosdistro>/<package_name>` -> `debian/<rosdistro>/<package_name>` -> `debian/<rosdistro>/<debian_version>/<package_name>`.

I believe the export patches is optional (good practice, but I think it should work with out it).

This is usually my process (I tested it out with `rviz` just to make sure):

1. Edit the files I want on the branch I want to patch, e.g.: https://github.com/wjwwood/rviz-release/commit/bbe09e600a97e2c638def9b8613ed776716ef1c2
2. Rerun bloom, e.g. `bloom-release -t indigo -r indigo rviz --override-release-repository-url https://github.com/wjwwood/rviz-release.git`
3. Check that it took:
  - https://github.com/wjwwood/rviz-release/commit/d9a270034344cabe1ec371f88372af8a3e683931
  - https://github.com/wjwwood/rviz-release/commits/release/indigo/rviz
  - https://github.com/wjwwood/rviz-release/blob/debian/indigo/rviz/CMakeLists.txt#L11
