### ISSUE TITLE
custom version suffix for internal builds

### ISSUE THREAD

**Issue by defunctzombie** [ros-infrastructure/bloom#390]
We have some internal patches for ros modules and I would like to create debian packages for those. The upstream versions for them are already specified in the changelog (i.e. 1.2.3) and when I apply our patches and build I want to be able to release as a package version (1.2.3-0company, 1.2.3-1company). This is the prefered approach in debian to add on to the version number and not increment the main version number ourselves.

However, bloom-generate rosdebian complains about a non-compliant title. Is there a way around that complaint or would you be open to a patch to allow such changelog entries?

**Comment by mikepurvis** [comment]
We're interested in this as well. We've ended up a) forking a lot of things and actually changing the name, so that we're free to do what we want with the version numbers and also b) endlessly incrementing the debian increment by reblooming the same upstream version over and over, but overriding the "upstream tag".

The second behaviour in particular is very problematic because bloom doesn't actually record what tag you it used to fetch the upstream, so it's only a matter of internal convention for us (see: https://github.com/clearpathrobotics/navigation/releases)

**Comment by defunctzombie** [comment]
I've done a bit of digging and it seems that this largely comes down to this regex (https://github.com/ros-infrastructure/catkin_pkg/blob/master/src/catkin_pkg/changelog.py#L298) which is responsible for parsing the changelog entries. If it handled some more cases or was more lax in the parsing then this would likely start to work. It is also possible that many other things expect the version to be #.#.# and will break otherwise but I haven't verified that.

**Comment by mikeferguson** [comment]
+1

**Comment by cottsay** [comment]
I know ROS doesn't officially have much support for Fedora, but you should know that putting non-numeric characters in the `M.m.r` version will break RPMs [1]. The recommendation is to use the "release" part of the version.

The recommendation for standard Semantic Versioning is also to use the release part [2].

--scott

[1] https://fedoraproject.org/wiki/Packaging:NamingGuidelines#Version_Tag
[2] http://semver.org/

**Comment by defunctzombie** [comment]
@cottsay Is there a way to codify the release part in the repo? The issue with not being able to do that is that I won't know what next version to release. I suppose in the case of internal use where I don't care about RPM and only use DEB then it would be a desirable feature. Patching the catkin_pkg worked for me.

**Comment by cottsay** [comment]
I actually did a quick test just now, and it looks as though while the Fedora guidelines suggest that you can't use alphabetic characters in the `M.m.r` version part, RPM does allow it, as does DNF/YUM. Since the RPMs we build for ROS don't *have* to follow Fedora packaging guidelines, I see no reason why we can't disregard this.

It would be great to see a "prefix" and "suffix" Bloom configuration parameter added which persists in the release repository for the package. It could be added automatically to the "inc" index during generation. If this isn't sufficient, though, I see no reason not to just patch `catkin_pkg` and suffix the `M.m.r` release part to meet your needs.

--scott

**Comment by defunctzombie** [comment]
@cottsay Cool! Ill send a PR over to `catkin_pkg` with the regex that worked for me. Right now I added the ability for the regex to support `M.m.r-##name` figuring folks could follow the pattern of `-<Increment><org>` suffix.

What is the release repository for a package? If I have forks of the package internally should I be keeping such a release repository for packages as well?

**Comment by defunctzombie** [comment]
Related PR for catkin_pkg https://github.com/ros-infrastructure/catkin_pkg/pull/145
