### ISSUE TITLE
Solution for `Is there a reason why dependencies get broken so often with ROS packages?`

### ISSUE THREAD

**Issue by k-okada** [ros-infrastructure/bloom#414]
Hi, 
I also had trouble on the broken ros package, as we discussed in http://lists.ros.org/pipermail/ros-release/2014-May/004477.html, `apt-get dist-upgrade` is the good solution, but most of users who got into this type of trouble do not run such command.
```
Most ROS maintainers (including me) do not make good use of the
``version_gte`` attribute. That means that down-level systems frequently
end up using out-of-date dependencies, which no longer work. The
dist-upgrade command helps mask this problem.
```
I thought if all package has version constraint in debian/control file, as below, then we can solve the probelm
```
(devel)k-okada@p40-yoga:/tmp/urg_node-release$ cat debian/control 
Source: ros-indigo-urg-node
Section: misc
Priority: extra
Maintainer: Chad Rockey <chadrockey@gmail.com>
Build-Depends: debhelper (>= 9.0.0), ros-indigo-catkin (>= 0.6.18-0), ros-indigo-diagnostic-updater (>= 1.8.10-0), ros-indigo-dynamic-reconfigure (>= 1.5.46-0), ros-indigo-laser-proc (>= 0.1.4-1), ros-indigo-nodelet (>= 1.9.8-0), ros-indigo-rosconsole (>= 1.11.20-0), ros-indigo-roscpp (>= 1.11.20-0), ros-indigo-sensor-msgs (>= 1.11.9-0), ros-indigo-tf (>= 1.11.8-0), ros-indigo-urg-c (>= 1.0.404-5)
Homepage: http://ros.org/wiki/urg_node
Standards-Version: 3.9.2

Package: ros-indigo-urg-node
Architecture: any
Depends: ${shlibs:Depends}, ${misc:Depends}, ros-indigo-diagnostic-updater (>= 1.8.10-0), ros-indigo-dynamic-reconfigure (>= 1.5.46-0), ros-indigo-laser-proc (>= 0.1.4-1), ros-indigo-nodelet (>= 1.9.8-0), ros-indigo-rosconsole (>= 1.11.20-0), ros-indigo-roscpp (>= 1.11.20-0), ros-indigo-sensor-msgs (>= 1.11.9-0), ros-indigo-tf (>= 1.11.8-0), ros-indigo-urg-c (>= 1.0.404-5)
Description: urg_node
```

I could not find a good way to get current version of the package, but if that is possible, we can fix bloom as follows
```
--- a/bloom/generators/debian/generator.py
+++ b/bloom/generators/debian/generator.py
@@ -184,7 +184,11 @@ def summarize_dependency_mapping(data, deps, build_deps, resolved_deps):
             info(template.format(key, resolved_deps[key]))
 
 
+from rosdep2.gbpdistro_support import get_gbprepo_as_rosdep_data
+g_data = get_gbprepo_as_rosdep_data('indigo')
+
 def format_depends(depends, resolved_deps):
@@ -194,12 +198,15 @@ def format_depends(depends, resolved_deps):
     }
     formatted = []
     for d in depends:
         for resolved_dep in resolved_deps[d.name]:
             version_depends = [k
                                for k in versions.keys()
                                if getattr(d, k, None) is not None]
             if not version_depends:
-                formatted.append(resolved_dep)
+                formatted.append("{0} (>= {1})".format(resolved_dep, g_data[d.name]['version']))
             else:
                 for v in version_depends:
                     formatted.append("{0} ({1} {2})".format(
```

How do you think.

**Comment by mikepurvis** [comment]
This would effectively force a dist-upgrade every time, which would avoid breakages but would also result in a _lot_ of unnecessary downloading/unpacking/upgrading of packages.

**Comment by tfoote** [comment]
Indeed we used to do complete version locking (down to the exact build timestamp) in the debian build process before we had support for versioned dependencies. Once we added that feature we relaxed the system constraints since as @mikepurvis pointed out it significantly increases overhead.

If you're running into packages that break due to missing a feature in a dependency that was added recently please ticket it on the package that is missing the version dependency. This is part of the responsibility of a package maintainer.

**Comment by k-okada** [comment]
thanks for clear explanation, I'll close the issue for now.

several comments are;
- I think version locking without build timestamp may not increase overhead as we had before with compete version locking. if we consider current problem happens to specially beginners, I think this overhead is tolerable. And for those who know how to use dist-upgrade, this solution may a reduce number of package to be installed compare to running dist-upgrade when the found it is required.
- It is hard for upstream library maintainer to check all downstream package that will affect by the change, and vice versa,  so usually we noticed that after release. https://github.com/ros-perception/vision_opencv/pull/130/files and https://github.com/ros-perception/image_pipeline/pull/239. I think people who uses shadow fixed will unconsciously run dist-upgrade or manually installs upstream packages and do not think this as a problem, so usually this becomes  
- Since 'official' package release roll out occurs every several month, we'll have to keep that broken situation for a that period. So I think we need some way not to relay 100% on maintainer work.

**Comment by mikepurvis** [comment]
The official package rollout is always a fully working set, since the buildfarm rebuilds downstream when a new version of a dependency comes out— eg, new version of catkin gets released and the entire tree rebuilds.

The debian metadata dependencies are just a matter of forcing users (or not) to update to the exact versions which are in that rolled-out set. With the current scheme, there's a choice to `dist-upgrade` every time or not bother— by locking in deps, you'd take away the choice.

Either way, if you don't care for this and have the capability/desire to run your own deployment infrastructure, you could check out bundling, which is what Clearpath is doing to deploy ROS workspaces these days. See ROSCon talk and demo (both me):

https://vimeo.com/187705228
https://github.com/mikepurvis/ros-bundling
