### ISSUE TITLE
Dependencies fail for rosdebian and interdependent workspace

### ISSUE THREAD

**Issue by zlacelle** [ros-infrastructure/bloom#542]
I'm building a driver for a sensor that has multiple packages within one repository (similar to how the ublox package works now). I'm attempting to use the "bloom-generate rosdebian" command to build installers for this package. I've had to fork and create my own rosdistro repo internally, but setting ROSDISTRO_URL fixes that issue. This process works well for single ROS packages that don't depend on other non-installed packages present in the catkin ws.

However, for this particular codebase, I want to build debians for each one whenever I release. Because they depend on each other (e.g. the driver needs msgs built first), they need to know where to find things like the .cmake files for the other packages. But, the bloom tool sources setup.sh in /opt/ros/<version>, which wipes out CMAKE_PREFIX_PATH, PYTHONPATH, etc.

I think that bloom-generate rosdebian should have an option to not blow away local workspace variables to allow for debian/rpm/etc package generation of interdependent ROS packages.

**Comment by zlacelle** [comment]
To add more information to this issue, if I manually edit the debian/rules file generated by bloom-generate rosdebian, the following does NOT work:

* Adding the local workspace's devel/ directory to CMAKE_PREFIX_PATH, i.e. CMAKE_PREFIX_PATH=/opt/ros/kinetic:/home/user/catkin_ws/devel

The following DOES work:

* Adding the _DIR variable for every local dependency individually, i.e. my_custom_package_msgs_DIR="/home/user/catkin_ws/devel/share/my_custom_package_msgs/cmake"

This is quite tedious for every package, and I believe that setting CMAKE_PREFIX_PATH should fix this, but for some reason it does not.

**Comment by tfoote** [comment]
The debian packaging pipeline is designed to produce binaries in full isolation so that they are as reproducible as possible. As such they are designed to not interact with local workspaces etc.

The standard technique for this is to build the dependency and then install it. After which you can build the higher level package on top of the installed version of the dependency. This is the most reliable way to make sure that they will be compatible. If you rely on the workspace version it's quite possible that you'll rely on uninstalled resources and thus the debian package is broken. 

Similarly, bloom only generates a sourcedeb and that sourcedeb is designed to be relocatable and buildable by any user using just it's declared dependencies as such inserting your workspace paths into any level of the packaging will break it for any other user.

Also note that bloom before it invokes the debian generator actually splits all the packages into individual branches to avoid this potential cross talk that leads to unreproducible results. I would recommend that you do the same, or just invoke bloom and let it do all the necessary steps and not try to just use a small part of the pipeline.

**Comment by zlacelle** [comment]
@tfoote Makes sense, and I was thinking of making this part of the process regardless. My hangup is that I feel that there's a bit of a difference between building, say, the messages and binaries packages both related to a single project versus building two custom packages from two different projects. I understand that you want to keep the pipeline the same, these scenarios just feel different.

I would note that the reason I'm not using the full bloom pipeline is because we're not indexing all of our packages publicly, and thus we can't use bloom without a few changes (e.g. our own rosdistro clone). While I have every intention of releasing, this isn't always an option, and the ROS packaging tools are quite nice to use. It would be good if they had a "private" method to use them.

When deploying multiple packages that are part of a single project simultaneously, especially those that have interdependencies, is this bloom process purely manual? I.e. the maintainer must individually manage their project dependencies, build from least dependent to most dependent, and push them up? Or how does the ROS build farm handle this internally. For example, suppose we're adding our new project and go through the bloom process and generate a release; how does the ROS build farm build/install the isolated messages package before the isolated driver package?

**Comment by tfoote** [comment]
> I would note that the reason I'm not using the full bloom pipeline is because we're not indexing all of our packages publicly, and thus we can't use bloom without a few changes (e.g. our own rosdistro clone). While I have every intention of releasing, this isn't always an option, and the ROS packaging tools are quite nice to use. It would be good if they had a "private" method to use them.

Supporting private releases is something that we designed into the system, but you're right that the main approach to that is to have a private extended rosdistro. I know of several active users of this functionality but the the overhead for that is not always worth it for a small number of packages as it sounds like your use case is. 

There are a few workaround tips I can suggest for you though. In particular you can setup your own custom rosdep source that will hardcode the package name translations for your packages instead of putting them into the rosdistro. This can be done locally on the machine where you're running bloom, but will also need to be propagated to all other machines that might want to refer to them by their binary names from their source names.

Overall we'd love to improve support for this use case but to put the significant effort in to support the private usage of the tools we'd need direct sponsorship. But we are definitely open to community contributions that can help extend the existing functionality, and are happy to review them and give feedback.

> When deploying multiple packages that are part of a single project simultaneously, especially those that have interdependencies, is this bloom process purely manual? I.e. the maintainer must individually manage their project dependencies, build from least dependent to most dependent, and push them up? Or how does the ROS build farm handle this internally. For example, suppose we're adding our new project and go through the bloom process and generate a release; how does the ROS build farm build/install the isolated messages package before the isolated driver package?

As long as the entries are in the rosdistro or rosdep database bloom's execution is not required to be in order. The sourcedeb it generates is not dependent on content from the other packages. However when that's picked up by the buildfarm it does carefully go through all the packages in order, and blocks downstream packages until all their upstream dependencies are resolved. (With a few race conditions since it's a large parallelized system.) Ever package's dependencies are reviewed and asserted to have been built prior to trying to build that package. And the generated installers all declare their dependencies appropriately and the packaging system asserts that they are all installed in the proper order.

**Comment by zlacelle** [comment]
Thanks for the info, I'll look into adding custom rosdep settings. I'll go ahead and close this issue. If I get together something useful as far as a guide for operating a private bloom packaging environment that remains almost the same as the public one, I'll try to find a place to post it.
