### ISSUE TITLE
Error: lib with so name 

### ISSUE THREAD

**Issue by LZMSTI** [ros-infrastructure/bloom#621]
Dear Author:
  Thanks for your amazing work, I have  encountered  an error while trying to create debs for ros package. In my CMakeLists.txt I add_library(<library-name> xxx) first, then I SET_TARGET_PROPERTIES(<library-name> PROPERTIES VERSION ${PROJECT_VERSION} SOVERSION ${PROJECT_VERSION_MAJOR}). 

After that I create debs, however an error occurs, "dpkg-shlibdeps: error: couldn't find library <library-name>.so.xxx needed by debian/ros-kinetic-<package>/opt/ros/kinetic/lib/<package>/<node> (ELF format: 'elf64-x86-64'; RPATH: '')"

coudl you please tell me how to deal with the problem? 

Thanks Sincerely!

**Comment by tfoote** [comment]
Please ask for help on answers.ros.org. When you ask the more complete your question is with enough information to reproduce your problem is the most likely to get a useful response. 

From reading your description you probably either have something that doesn't reference the file with the new name, or might be missing an install rule. Please take a look and ask with more detailed debugging information in the question. With this level of description all we can do is guess what you're doing and why it's not doing what you want it to do.

Suggestions for a good question can be foound at https://wiki.ros.org/Support
