### ISSUE TITLE
Generate machine-readable `debian/copyright` file

### ISSUE THREAD

**Issue by emersonknapp** [ros-infrastructure/bloom#645]
As of https://www.debian.org/doc/packaging-manuals/copyright-format/1.0/ there is an official specification for a machine-readable `copyright` file. This allows for easier automated inspection of dependency licensing.

I'm not sure exactly how difficult this change would be - I have found that the `copyright` file was added in https://github.com/ros-infrastructure/bloom/pull/470 so that's a place to start investigation.

Would there be any reason against making this change, assuming it's not very complex?

**Comment by cottsay** [comment]
Hi @emersonknapp, I've done some investigation and prototyping, and I think we have a pretty good handle on the scope of this work. To that end, we need to make some decisions about how to move forward in a way that will meet the needs of your use case in a timely fashion.

The short story is that as expected, [REP 149 (package.xml v3)](https://www.ros.org/reps/rep-0149.html) manifests do not contain all of the information we need in order to minimally populate a machine-readable debian copyright file according to the specifications. Namely, there are three missing values:
1. The actual copyright statement should contain names of copyright holders with the year of the copyright for all files associated with the specified license.
2. The glob pattern to match against the source tree which describes which files are covered by a specified license.
3. The full text or a reference to the full text of a specified license is not a required attribute in a REP 149 manifest and is rarely present.

We will need to update the package manifest specifications to include this information in some way. I don't think we should get into the details of how exactly that should be done in this thread. We have other manifest changes in the works, and that discussion should happen on the REP repository.

We should, however, decide how to handle the absence of this information both while we wait for a mechanism in the manifest to become available for us to populate it, and also when encountering a manifest of v3 or prior, where we will never have all of the information we want. We should not expect that the new manifest specification will be a breaking change and should therefore expect future ROS distributions to contain both new and older manifests.

We've discussed a few approaches to dealing with under-specified manifests:
1. Revert to previous behavior and do not generate a machine readable copyright file. This is the "safest" thing that we can do, but it means that there is a substantial amount of work (time) before the machine readable copyright files can be used in a meaningful way.
2. Break from the specification and omit the fields that we can't populate accurately. This would likely also mean omitting the `Format` field from the header because we will no longer be compliant, also meaning that many parsers will not consider the copyright file to be machine-readable at all. We'd essentially be deriving our own format which is a subset of the published v1 format of the copyright file.
3. Use placeholders in fields which we can't populate accurately so that the generated copyright file complies with the schema insofar as a parser would successfully parse the file. While we may be able to come up with reasonable placeholders, we'd be violating the spirit of parts of the specification and in some cases may be incorrect. The most notable advantage is nearly immediate usability. Some possible placeholders:
   * `Copyright:`
     - Use a concatenation of the `<authors>` if available
     - A verbatim message, such as `See package copyright in source code for details`
   * `Files:`
     - Over specify, and assume that all files in the package are covered by the license using `*`. This will probably be correct more often than not, but is almost always incorrect when multiple licenses are specified in the manifest.
     - Specify the path to the license file itself, if available
   * `License:` full text
     - A verbatim message, such as `See repository for full license text`. Note that the repository URL, if specified in the manifest, is part of the header in the copyright file as an optional field.

There are probably other approaches that we can take. Regardless, the decision will be influenced by what you're trying to do with the files, so I'd like to hear thoughts from you and your team.

**Comment by emersonknapp** [comment]
I think we would prefer to use the Option 3 approach, of having placeholder text for the fields that are underspecified. This makes it easy to parse the files with common tooling, and if the language is consistent, we can know that those specific fields are "unknown".

Given this, I think the following works well for the understpecified fields you've listed:
* `Copyright`: verbatim `See package copyright in source code for details` is fine
* `Files`: underspecify, just point out the LICENSE files
* `License` full text: `See repository for full license text` works fine

**Comment by nuclearsandwich** [comment]
> `Files`: underspecify, just point out the LICENSE files

@cottsay how would this work for compound repositories that only have a top-level license file which thus isn't included in the release sources? Would we just circularly point back to the generated debian/copyright file?

Rather than pointing to the license file, which as discussed offline, may itself be public domain text and not covered by itself, could we select another bogus value like `See repository for full license details`? That would have the benefit of being a hard-coded string like the other fields we can't supply.

---

I'm quite hesitant to generate something, call it a "Debian copyright-formatted file" and then not include specification-conformant data. Personally I would lean toward not generating anything that could be mistaken for a valid debian/copyright file if we can't do so.

I think we need to be careful in all of our messaging and documentation, _especially_ changelogs and commit messages, to refer to a Debian copyright "inspired" format that conforms to [deb822](https://man7.org/linux/man-pages/man5/deb822.5.html).

My second major concern with the outlined plan is that there is no vehicle for a package author to write a complete debian/copyright conformant file and include it in the appropriate place.
With bloom as is, a package.xml tag of `<license file="package.copyright">Apache-2.0</license>` would install the package.copyright file as debian/copyright directly. This means that behavior would actually regress for any package maintainers who want to proactively provide a valid debian/copyright file. They could still do so by adding patches to the bloom template branches but that's quite a step up in complexity to achieve the desired result.

What are thoughts on enhancing the feature to try and deb822 parse the given license file and see if it 1. is deb822 valid and 2. declares `Format: https://www.debian.org/doc/packaging-manuals/copyright-format/1.0/` and passing it through unchanged in that case?

**Comment by j-rivero** [comment]
> I'm quite hesitant to generate something, call it a "Debian copyright-formatted file" and then not include specification-conformant data. Personally I would lean toward not generating anything that could be mistaken for a valid debian/copyright file if we can't do so.

I (sadly) have to agree that we are forcing things too much to claim a valid https://www.debian.org/doc/packaging-manuals/copyright-format/1.0/ file. Definitely not something that Debian/Ubuntu would allow officially in any way.

> My second major concern with the outlined plan is that there is no vehicle for a package author to write a complete debian/copyright conformant file and include it in the appropriate place.
With bloom as is, a package.xml tag of <license file="package.copyright">Apache-2.0</license> would install the package.copyright file as debian/copyright directly. This means that behavior would actually regress for any package maintainers who want to proactively provide a valid debian/copyright file.

I'm not sure if someone is doing this, but reading [REP 149](https://www.ros.org/reps/rep-0149.html#license-multiple-but-at-least-one):

```
file="FILE" (optional)

    A path relative to the package.xml file containing the full license text.
    Many licenses require including the license text when redistributing the software. E.g. the Apache License, Version 2.0 states in paragraph 4.1:
```

I think that providing anything different than "the full license text" in the `file` attribute would be abusing the spec and probably was not the spirit of that attribute.

> They could still do so by adding patches to the bloom template branches but that's quite a step up in complexity to achieve the desired result.

This is probably the "right" way of including a debian/copyright file compliant with https://www.debian.org/doc/packaging-manuals/copyright-format/1.0/ today.

I still think that we can improve things over the current state, make a machine parsable file and reuse our current work. My proposal would be to go with @emersonknapp's suggestion on the `Copyright`, `Files` and `License` but since we can not claim to be compliant with `copyright-format/1.0` changing `Format:` to be something like: `Bloom subset of https://www.debian.org/doc/packaging-manuals/copyright-format/1.0/`.

This should allow main parsers (ones using [python3-debian](https://salsa.debian.org/python-debian-team/python-debian/-/blob/master/lib/debian/copyright.py#L667-668)) to work with a warning but not fail:
```
(debian-sid)jrivero@nium $ (master) decopy
Building tree: 27dir [00:00, 13025.79dir/s]
/usr/lib/python3/dist-packages/debian/copyright.py:670: UserWarning: format not known: 'Bloom subset of https://www.debian.org/doc/packaging-manuals/copyright-format/1.0/'
  warnings.warn('format not known: %r' % fmt)
...

**Comment by nuclearsandwich** [comment]
> I think that providing anything different than "the full license text" in the `file` attribute would be abusing the spec and probably was not the spirit of that attribute.

I think that by and large that use case is the most common and it was certainly the motivation for adding the field. But I don't think that setting the file to a debian/copyright formatted one for licenses other than Apache-2.0 is incorrect rather than unexpected.

> I still think that we can improve things over the current state, make a machine parsable file and reuse our current work. My proposal would be to go with @emersonknapp's suggestion on the `Copyright`, `Files` and `License` but since we can not claim to be compliant with `copyright-format/1.0` changing `Format:` to be something like: `Bloom subset of https://www.debian.org/doc/packaging-manuals/copyright-format/1.0/`.

I can live with that. There's clear preference for a parseable data format even if it's not sufficient to automate license and copyright checking without manual review. The only thing I'm still hung up on is using the license path in the `File:` field. I 

Instead of
>     * `Files`: underspecify, just point out the LICENSE files

I would propose something that is constant just like we are doing for the other fudged fields. I'm not too concerned with what the constant value is, I just pulled my suggestsion of a hat when looking at the other fields.

> Rather than pointing to the license file, which as discussed offline, may itself be public domain text and not covered by itself, could we select another bogus value like `See repository for full license details`? That would have the benefit of being a hard-coded string like the other fields we can't supply.

**Comment by emersonknapp** [comment]
Would it be possible to leave the fields "present, but empty" when we don't have enough information to fill them out? 

I think we'd be fine with constants, and also be fine with missing information - as long as our scripts could notice and flag that missing information for us.

> What are thoughts on enhancing the feature to try and deb822 parse the given license file and see if it 1. is deb822 valid and 2. declares Format: https://www.debian.org/doc/packaging-manuals/copyright-format/1.0/ and passing it through unchanged in that case?

That would be just fine

> be something like: Bloom subset of https://www.debian.org/doc/packaging-manuals/copyright-format/1.0/.

I can also live with that

**Comment by cottsay** [comment]
> Would it be possible to leave the fields "present, but empty" when we don't have enough information to fill them out?

We discussed this option offline. From what I'm reading, this would constitute a formatting violation, which seems pretty risky as far as parser compatibility is concerned. I believe placeholder text would be safer, at least at this stage.
